name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt5
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        cache: true 
        # Don't redownload if the files are available (still sets up the enviromnent).
        # This reduces ~5 mins (first time) to ~3 mins.
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

